version: "3.8"

services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
     - 27017:27017
    volumes:
     - mongodb_data:/data/db
    networks:
     - mynetwork  # Attach this service to the mynetwork

  springboot-mongodb:
    image: springboot-mongo:latest
    container_name: springboot-mongodb
    ports:
      - 8080:8080
    networks:
     - mynetwork  # Attach this service to the same network

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data:
  
