#version: "3.8"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
     - 27017:27017
  springboot-mongodb:
    image: techcloudifyme/springboot-mongodb:latest
    container_name: springboot-mongodb
    ports:
      - 8080:8080
    links:
      - mymongodb  
